In [178]:
import duckdb

# one‐liner to grab everything under data/logs/signals/*.parquet
df = duckdb.query("""
    SELECT *
    FROM parquet_scan('data/logs/trades/*.parquet')
""").to_df()

In [179]:
df

Empty DataFrame
Columns: [time, mint, action, price, size, cash, gain_abs, gain_pct]
Index: []

In [180]:
pd.read_csv('data/logs/trades/all_trades.csv')

,time,mint,action,price,size,cash,gain_abs,gain_pct
0,2025-05-18 21:26:00,6pEEb9oyxqD4eWEUytwiusBzSSsaX5JMoYMJcvEJpump,BUY,3.197077e-08,3.112218e+10,9000.000000,NaN,NaN
1,2025-05-18 21:26:00,DsJCZ6JTdcbaTJQ7PcguTUdC9uEFNsrEzVXy9zmnpump,BUY,3.302450e-08,1.976773e+10,5904.900000,NaN,NaN
2,2025-05-18 21:26:00,6xv4H8U1z2CrnsitPMfS6dWXph9gsv8u4AfZySPWpump,BUY,9.877071e-08,5.353650e+09,4782.969000,NaN,NaN
3,2025-05-18 21:26:00,GBBF92P4bTRGDtTVbqYrfFbucygEWrgmm75CLHLNpump,BUY,2.832931e-08,1.511914e+10,3874.204890,NaN,NaN
4,2025-05-18 21:26:00,HS7B9w9eutyEg1gmx5d7KxqwFmBG7wbT2tdoZqV1pump,BUY,3.250300e-08,1.464189e+10,4304.672100,NaN,NaN
...,...,...,...,...,...,...,...,...
2109,2025-05-18 22:16:00,92JVwkVuZ9h8dkpuA2xNfXsFCrWof8VjfLBSUAm9pump,SELL,1.097359e-07,1.130564e+09,1230.672178,1.653120,1.350474
2110,2025-05-18 22:17:00,4rdkGfsXXVg8P5tB9Mm9DY62S4mgsNz96njeFv23pump,BUY,3.036020e-08,4.033302e+09,1107.604961,NaN,NaN
2111,2025-05-18 22:18:00,4rdkGfsXXVg8P5tB9Mm9DY62S4mgsNz96njeFv23pump,SELL,3.037687e-08,4.033302e+09,1229.511451,0.067204,0.054882
2112,2025-05-18 22:20:00,7K1bPNAY5Q8mXhQQH11582rPZMio8Nd6mRf2774Lpump,BUY,5.026923e-08,2.433624e+09,1106.560306,NaN,NaN
2113,2025-05-18 22:21:00,7K1bPNAY5Q8mXhQQH11582rPZMio8Nd6mRf2774Lpump,SELL,5.316780e-08,2.433624e+09,1235.303766,7.054023,5.766087

In [84]:
import os
import pandas as pd
from pathlib import Path

# point this at your raw dir
RAW_PATH = Path('data/logs/raw/')  

# grab every .parquet file
parquet_files = list(RAW_PATH.glob("*.parquet"))

# read ’em all into a list of DataFrames
df_list = []
for p in parquet_files:
    df = pd.read_parquet(p)
    df["mint"] = p.stem
    df_list.append(df)

# stitch into one big DataFrame
full_df = pd.concat(df_list, axis=0)

# optional: sort by timestamp index
full_df.sort_index(inplace=True)

In [85]:
full_df

,mint,open,high,low,close,volume,slot,is_5_min,is_1_min
timestamp,,,,,,,,,
2025-05-18 17:39:00,GW5VscCRBywGbUCC9zkTWsGXMWBrxSaFSBUjXsFbpump,2.795800e-08,3.278554e-08,2.795800e-08,2.902959e-08,2717077956,340880644,False,True
2025-05-18 17:39:00,4XRQYGiCskVeLJJvntM98ezLSfdr7uArrHwPdGTbpump,2.795800e-08,2.947277e-08,2.795800e-08,2.947277e-08,612771582,340880627,False,True
2025-05-18 17:39:00,284yS35ubqkBdKmvy4KXJVGiPMa4uaMQLBCXapmipump,2.795800e-08,3.208039e-08,2.795800e-08,3.208039e-08,4115242935,340880661,False,True
2025-05-18 17:39:00,BH3ZPkKXEenBfBjrLHewYiKBiuQAexipXb9mDn3kpump,2.795800e-08,2.983493e-08,2.795800e-08,2.983493e-08,1980198018,340880694,False,True
2025-05-18 17:39:00,HV7hnn47q2LsYQqxLyfGYfX6n3E8s21AKYnAyMXSpump,2.795800e-08,3.017540e-08,2.795800e-08,3.017540e-08,2010779009,340880624,False,True
...,...,...,...,...,...,...,...,...,...
2025-05-18 18:26:00,AHdzWiSQZwgfp78NJBN6JmaFwNFpKugBHcM546hwpump,2.812991e-08,2.801800e-08,2.801800e-08,2.801800e-08,119832922,340887680,False,True
2025-05-18 18:26:00,B4ezBkd7XqnMFWMKCTDwo95VpsezihAiumyLeCzupump,3.118016e-08,3.109244e-08,3.102297e-08,3.102297e-08,124553302,340887729,False,True
2025-05-18 18:26:00,9VNnneud95kY9P6VBMhidtLNBNF4EWj3nGoBDyZopump,1.382972e-07,1.483758e-07,1.301907e-07,1.481857e-07,9449024675,340887662,False,True
2025-05-18 18:27:00,Fu2fYA3Lc7ZPDQQb5E1rQqHGmcdyXFv3rqPMYBb2pump,1.126044e-07,1.065331e-07,1.007703e-07,1.007703e-07,4936010661,340887816,False,True
2025-05-18 18:28:00,8RkgtWkKAfrxDL86VTdyo4hhXmqV9MZ5PQFE7nY9pump,2.871733e-08,2.811891e-08,2.811891e-08,2.811891e-08,635175756,340887993,False,True